name: Generate pages

on:
  push:
    branches: [ main ]

jobs:
  gen:
    runs-on: ubuntu-latest
    env:
      PAT: ${{ secrets.PAT }}
    steps:
      - name: Checkout wiki
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: wiki
      - name: Checkout publishing
        uses: actions/checkout@v2
        with:
          path: _out
          repository: osdev-wiki/osdev-wiki.github.io
          token: "${{ secrets.PAT }}"
      - name: Install Node.js
        uses: actions/setup-node@v2.5.0
      - name: Install Antora
        run: npm install -g @antora/cli@2.3 @antora/site-generator-default@2.3
      - name: Clean _out
        run: |
          cd _out
          find . -not -path './.git/*' -not -path ./.git -delete
          echo osdev.wiki > CNAME
      - name: build site
        run: |
          cd wiki
          npm exec antora -- generate --to-dir ../_out antora-playbook.yml
      - name: Publish
        run: |
          set -xe
          export COMMIT_HASH="$(git -C wiki rev-parse HEAD)"
          cd _out
          git config user.name  "Wiki Autobuild"
          git config user.email "autobuild@osdev.wiki"
          git add .
          git commit -m "$COMMIT_HASH"
          git push
