name: Generate pages

on:
  push:
    branches: [ main ]

jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout wiki
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: wiki
      - name: Get deps
        run: |
          set -xe
          gem install --user-install asciidoctor
          pip install --user -U Pygments
      - name: Checkout publishing
        uses: actions/checkout@v2
        with:
          path: _out
          repository: osdev-wiki/osdev-wiki.github.io
          fetch-depth: 0
          token: "${{ secrets.PAT }}"
        if: ${{ github.repository == 'osdev-wiki/wiki' }}
      - name: Checkout publishing (for fork)
        uses: actions/checkout@v2
        with:
          path: _out
          token: "${{ github.token }}"
          fetch-depth: 0
          ref: gh-pages
        if: ${{ github.repository != 'osdev-wiki/wiki' }}
      - name: Cache stack
        uses: freckle/stack-cache-action@09a5fa43f7a720659ee8489a270837ed40ccc869
        with:
          working-directory: wiki/generator
      - name: Clean _out
        run: |
          cd _out
          find . -not -path './.git/*' -not -path ./.git -delete
          echo osdev.wiki > CNAME
          touch .nojekyll
      - name: Build site
        run: |
          export GEM_HOME="$(ruby -e 'puts Gem.user_dir')"
          export PATH="$GEM_HOME/bin:$HOME/.local/bin:$PATH"
          cd wiki/generator
          stack run --cwd .. -- build
          cd ..
          mv -T _out ../_site
      - name: Publish
        run: |
          set -xe
          export COMMIT_HASH="$(git -C wiki rev-parse HEAD)"
          cd _out
          git config user.name  "Wiki Autobuild"
          git config user.email "autobuild@osdev.wiki"
          git add .
          git commit -m "$COMMIT_HASH"
          git push
